apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-fss-proxy
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-fss-proxy.dev-fss-pub.nais.io
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-soknad-api
          cluster: dev-gcp
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

